distributed:
    backend: gloo
    world_size: 1
    master_addr: localhost
    master_port: '12345'
algo:
    cls_name: PPO
    cls_args:
        seg_len: 256
        opt_epochs: 3
        learner_batch_size: 64
        clip_param_init: 0.2
        clip_param_final: 0.0
        ent_coef_init: 0.01
        ent_coef_final: 0.01
        vf_loss_coef: 1.0
        vf_loss_cls: MSELoss
        vf_loss_clipping: False
        vf_simple_weighting: True
        credit_assignment_spec:
            extrinsic:
                cls_name: GAE
                cls_args: {gamma: 0.99, lambda_: 0.95, use_dones: True}
        extra_steps: 0
        standardize_adv: True
        use_pcgrad: False
        stats_window_len: 100
        checkpoint_frequency: 25600
        non_learning_steps: 0
        max_steps: 10000000
env:
    wrappers:
        train:
            AtariWrapper:
                use_noop: True
                use_sticky_actions: False
            DeepmindWrapper:
                episode_life: True
                clip_rewards: True
                frame_stack: True
                lazy: False
        evaluate:
            AtariWrapper:
                use_noop: True
                use_sticky_actions: False
            DeepmindWrapper:
                episode_life: False
                clip_rewards: False
                frame_stack: True
                lazy: False
networks:
    policy:
        net:
            preprocessing:
                ToChannelMajor: {}
            architecture:
                cls_name: NatureCNN
                cls_args: {img_channels: 4}
                w_init_spec: ['orthogonal_', {gain: 1.4142}]  # sqrt 2
                b_init_spec: ['zeros_', {}]
            predictors:
                policy:
                    cls_name: CategoricalPolicyHead
                    cls_args: {num_features: 512}
                    head_architecture_cls_name: Linear
                    head_architecture_cls_args: {}
                    w_init_spec: ['orthogonal_', {'gain': 0.01}]
                    b_init_spec: ['zeros_', {}]
                value_extrinsic:
                    cls_name: SimpleValueHead
                    cls_args: {num_features: 512}
                    head_architecture_cls_name: Linear
                    head_architecture_cls_args: {}
                    w_init_spec: ['orthogonal_', {'gain': 0.01}]
                    b_init_spec: ['zeros_', {}]
        optimizer:
            cls_name: Adam
            cls_args: {lr: 0.001, betas: [0.90, 0.999], eps: 0.00001}
        scheduler:
            cls_name: OneCycleLR
            cls_args:
                max_lr: 0.001
                total_steps: 4883
                pct_start: 0.0
                anneal_strategy: linear
                cycle_momentum: False
                div_factor: 1.0
    value:
        use_shared_architecture: True