version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - run:
          name: "Install system dependencies"
          command: |
            sudo apt-get update
            sudo apt-get install -y libglu1-mesa-dev libgl1-mesa-dev libosmesa6-dev xvfb ffmpeg curl patchelf libglfw3 libglfw3-dev cmake libjpeg-dev zlib1g zlib1g-dev swig python3-dev
      - run:
          name: "Install python dependencies"
          command: |
            pip install --upgrade pip
            pip install -e .
      - run:
          name: "Run unit tests"
          command: |
            mkdir test-results
            pytest
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  build-workflow:
    jobs:
      - build